### ISSUE TITLE
'statusMessage' is not defined

### ISSUE THREAD

**Issue by alejandrodt** [fe80Grau/Rectificarr#7]
Hi!
i am testing the app, and i am receiving the following error:

`Traceback (most recent call last):
  File "/opt/Rectificarr/main.py", line 140, in <module>
    if not "wasn't grabbed by Radarr" in statusMessage:
                                         ^^^^^^^^^^^^^
NameError: name 'statusMessage' is not defined`

If i try to print the statusMessage in order to know what happen:

`Traceback (most recent call last):
  File "/opt/Rectificarr/main.py", line 131, in <module>
    print(item['statusMessages'][0]['messages'][0])
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

do you know how to solve it? The full code is:

`Rectificarr is running...
Processing data from Radarr
{'movieId': 3, 'movie': {'title': '300', 'originalTitle': '300', 'originalLanguage': {'id': 1, 'name': 'English'}, 'alternateTitles': [{'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '300: The IMAX Experience', 'id': 5}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '300: Bitva u Thermopyl', 'id': 6}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '300 ขุนศึกพันธุ์สะท้านโลก', 'id': 7}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '斯巴達三百勇士', 'id': 8}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': 'Tres-cents', 'id': 9}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': 'Trois Cent', 'id': 10}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '300 Спартанцев', 'id': 11}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '300壯士：斯巴達的逆襲', 'id': 12}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '300 - Eroii de la Termopile', 'id': 13}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '戰狼300', 'id': 14}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '斯巴达三百勇士', 'id': 15}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': 'Spartan 300 Warriors', 'id': 16}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': '(300) Three Hundred', 'id': 17}, {'sourceType': 'tmdb', 'movieMetadataId': 3, 'title': 'Three Hundred', 'id': 18}], 'secondaryYear': 2006, 'secondaryYearSourceId': 0, 'sortTitle': '300', 'status': 'released', 'overview': 'Based on Frank Miller\'s graphic novel, "300" is very loosely based the 480 B.C. Battle of Thermopylae, where the King of Sparta led his army against the advancing Persians; the battle is said to have inspired all of Greece to band together against the Persians, and helped usher in the world\'s first democracy.', 'inCinemas': '2007-03-07T00:00:00Z', 'physicalRelease': '2007-06-14T00:00:00Z', 'digitalRelease': '2010-05-01T00:00:00Z', 'releaseDate': '2007-06-14T00:00:00Z', 'images': [{'coverType': 'poster', 'remoteUrl': 'https://image.tmdb.org/t/p/original/h7Lcio0c9ohxPhSZg42eTlKIVVY.jpg'}, {'coverType': 'fanart', 'remoteUrl': 'https://image.tmdb.org/t/p/original/fPg31FANBYhrV2z0vZB4nIonKbI.jpg'}], 'website': 'http://300themovie.warnerbros.com', 'year': 2007, 'youTubeTrailerId': 'UrIbxk7idYA', 'studio': 'Virtual Studios', 'path': '/mnt/12TBa/data/torrents/movies/300 [BluRay 1080p][AC3 5.1 Castellano AC3 5.1-Ingles+Subs][ES-EN]', 'qualityProfileId': 6, 'movieFileId': 0, 'monitored': True, 'minimumAvailability': 'released', 'isAvailable': True, 'folderName': '/mnt/12TBa/data/torrents/movies/300 [BluRay 1080p][AC3 5.1 Castellano AC3 5.1-Ingles+Subs][ES-EN]', 'runtime': 116, 'cleanTitle': '300', 'imdbId': 'tt0416449', 'tmdbId': 1271, 'titleSlug': '1271', 'certification': '18', 'genres': ['Action', 'Adventure', 'War'], 'tags': [], 'added': '2024-10-05T18:09:32Z', 'ratings': {'imdb': {'votes': 874109, 'value': 7.6, 'type': 'user'}, 'tmdb': {'votes': 13538, 'value': 7.2, 'type': 'user'}, 'metacritic': {'votes': 0, 'value': 52, 'type': 'user'}, 'rottenTomatoes': {'votes': 0, 'value': 61, 'type': 'user'}}, 'collection': {'title': '300 Collection', 'tmdbId': 125570}, 'popularity': 46.587, 'lastSearchTime': '2024-10-06T08:42:40Z', 'id': 3}, 'languages': [{'id': 3, 'name': 'Spanish'}], 'quality': {'quality': {'id': 7, 'name': 'Bluray-1080p', 'source': 'bluray', 'resolution': 1080, 'modifier': 'none'}, 'revision': {'version': 1, 'real': 0, 'isRepack': False}}, 'customFormats': [], 'customFormatScore': 0, 'size': 0, 'title': '300 [BluRay 1080p][AC3 5.1 Castellano AC3 5.1-Ingles+Subs][ES-EN]', 'sizeleft': 0, 'timeleft': '00:00:00', 'estimatedCompletionTime': '2024-10-06T09:35:20Z', 'added': '2024-10-06T08:42:46Z', 'status': 'completed', 'trackedDownloadStatus': 'warning', 'trackedDownloadState': 'importBlocked', 'statusMessages': [{'title': 'One or more movies expected in this release were not imported or missing', 'messages': []}, {'title': '300BD1080.www.newpct1.com.mkv', 'messages': ['Unable to parse file']}], 'downloadId': 'D52E8E0FC587A1663C5C00E1C9B22216D397F7EF', 'protocol': 'torrent', 'downloadClient': 'rdtclient', 'downloadClientHasPostImportCategory': False, 'indexer': 'dontorrent', 'outputPath': '/mnt/12TBa/data/torrents/movies/300 [BluRay 1080p][AC3 5.1 Castellano AC3 5.1-Ingles+Subs][ES-EN]/', 'id': 2094271471}
Traceback (most recent call last):
  File "/opt/Rectificarr/main.py", line 138, in <module>
    if not "wasn't grabbed by Radarr" in statusMessage:
                                         ^^^^^^^^^^^^^
NameError: name 'statusMessage' is not defined`


thanks!

**Comment by alejandrodt** [comment]
I made some prints:

`print(len(item['statusMessages']))`
Result: 
2

`print((item['statusMessages']))`
Result: 
[{'title': 'One or more movies expected in this release were not imported or missing', 'messages': []}, {'title': '300BD1080.www.newpct1.com.mkv', 'messages': ['Unable to parse file']}]

`print((item['statusMessages'][0]))`
Result: 
{'title': 'One or more movies expected in this release were not imported or missing', 'messages': []}

`print((item['statusMessages'][0]['messages'][0]))`
Result: 
Traceback (most recent call last):
  File "/opt/Rectificarr/main.py", line 127, in <module>
    print(item['statusMessages'][0]['messages'][0])
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range


is because the message is empty on the first row ???
